--실습 1
SELECT DEPTNO,
       TRUNC(AVG(SAL),0) AS AVG_SAL,
       MAX(SAL) AS MAX_SAL,
       MIN(SAL) AS MIN_SAL,
       COUNT(DEPTNO) AS CNT
FROM EMP
GROUP BY DEPTNO;

--실습 2
SELECT JOB,
       COUNT(*) 
FROM EMP
GROUP BY JOB
    HAVING COUNT(JOB) >= 3;
    
--실습 3
SELECT DISTINCT TO_CHAR(HIREDATE, 'YYYY') AS HIRE_YEAR,
       DEPTNO,
       COUNT(ENAME)
FROM EMP
GROUP BY TO_CHAR(HIREDATE, 'YYYY'), DEPTNO;

--실습 4
SELECT NVL2(COMM, 'O','X'),
       COUNT(ENAME)
FROM EMP
GROUP BY NVL2(COMM, 'O','X');

-- 실습 5
SELECT  DEPTNO ,  
        TO_CHAR(HIREDATE, 'YYYY'),
        COUNT(DEPTNO) AS CNT,
        MAX(SAL) AS MAX_SAL,
        SUM(SAL) AS SUM_SAL,
        ROUND(AVG(SAL),11) AS AVG_SUL
FROM EMP
GROUP BY ROLLUP(DEPTNO,TO_CHAR(HIREDATE, 'YYYY'));