--실습 1
SELECT JOB , E.EMPNO, E.ENAME , E.SAL, DEPTNO, D.DNAME
FROM EMP E NATURAL JOIN DEPT D
WHERE JOB = (SELECT JOB
             FROM EMP
             WHERE ENAME = 'ALLEN');
--값이 여러개 존재하면 = 보다 IN 사용 

--실습2
SELECT E.EMPNO, E.ENAME, D.DNAME, E.HIREDATE, D.LOC, E.SAL, G.GRADE
FROM EMP E NATURAL JOIN DEPT D NATURAL JOIN SALGRADE G
WHERE SAL > (SELECT AVG(SAL) FROM EMP)
AND E.SAL BETWEEN G.LOSAL AND G.HISAL
ORDER BY SAL DESC ,EMPNO;

--실습3
SELECT E.EMPNO, E.ENAME, E.JOB, E.DEPTNO, D.DNAME, D.LOC
FROM EMP E , DEPT D
WHERE E.DEPTNO = 10
AND E.DEPTNO = D.DEPTNO
AND E.JOB NOT IN  (SELECT JOB
                     FROM EMP
                    WHERE DEPTNO = 30);

--실습4
SELECT E.EMPNO, E.ENAME, E.SAL, G.GRADE
FROM EMP E, SALGRADE G
WHERE E.SAL BETWEEN G.LOSAL AND G.HISAL
AND SAL > (SELECT MAX(SAL)
            FROM EMP
            WHERE JOB = 'SALESMAN')
ORDER BY E.EMPNO;
--MAX(SAL) 미사용시
SELECT E.EMPNO, E.ENAME, E.SAL, G.GRADE
FROM EMP E, SALGRADE G
WHERE E.SAL BETWEEN G.LOSAL AND G.HISAL
AND SAL > ALL(SELECT DISTINCT (SAL)
                FROM EMP
               WHERE JOB = 'SALESMAN')
ORDER BY E.EMPNO;