--실습 1
CREATE TABLE EMP_HW(
EMPNO   NUMBER(4),
ENAME   VARCHAR(10),
JOB     VARCHAR(9),
MGR     NUMBER(4),
HIREDATE DATE,
SAL     NUMBER(7,2),
COMM    NUMBER(7,2),
DEPTNO  NUMBER(2)
);
DESC EMP_HW;
--실습2
ALTER TABLE EMP_HW
ADD  BINGO VARCHAR(20);
--실습3
ALTER TABLE EMP_HW
MODIFY BINGO VARCHAR(30);
--실습4
ALTER TABLE EMP_HW
RENAME  COLUMN BINGO TO REMARK;
--실습 5
INSERT INTO EMP_HW (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, REMARK)
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, NULL
FROM   EMP E;

SELECT * FROM EMP_HW;
--실습 6
DROP TABLE EMP_HW;
DESC EMP_HW;