--실습1
CREATE TABLE EMPIDX
AS (SELECT * 
     FROM EMP);
SELECT * FROM EMPIDX;
--실습2
CREATE INDEX IDX_EMPIDX_EMPNO
    ON EMPIDX(EMPNO);
    
SELECT * FROM USER_IND_COLUMNS;

DROP TABLE EMPIDX;
--실습3
CREATE VIEW EMPIDX_OVER15K
AS (SELECT EMPNO, ENAME, JOB, DEPTNO, SAL,
    NVL2(COMM, 'O','X') AS COMM
    FROM EMPIDX
    WHERE SAL > 1500);

SELECT *
FROM EMPIDX_OVER15K;
    
