--실습1
SELECT EMPNO, 
        RPAD(SUBSTR(EMPNO,0,2), 4, '*')  AS MASKING_EMPNO,
        ENAME,
        SUBSTR(ENAME,2,4) || '****' AS MAKING_ENAME
FROM EMP
WHERE LENGTH(ENAME) >= 5 
AND LENGTH(ENAME) <6;
       
--실습2
SELECT EMPNO, ENAME, SAL,
       TRUNC((TO_NUMBER(SAL)/21.5),2) AS DAY_PAY,
       ROUND((TO_NUMBER(SAL)/21.5/8),1) AS TIME_PAY
FROM EMP;

--실습 3
SELECT EMPNO, ENAME,
       TO_CHAR(HIREDATE, 'YYYY/MM/DD') AS HIREDATE,
       TO_CHAR(NEXT_DAY(ADD_MONTHS(HIREDATE, 3),'월요일'),'YYYY/MM/DD') AS R_JOB,
       NVL2(COMM, COMM||' ', 'N/A') AS COMM
FROM EMP;

--실습 4
SELECT EMPNO, ENAME,MGR,
       CASE 
       WHEN MGR IS NULL THEN '0000'
       WHEN SUBSTR(MGR,0,2) = '75' THEN '5555'
       WHEN SUBSTR(MGR,0,2) = '76' THEN '6666' 
       WHEN SUBSTR(MGR,0,2) = '77' THEN '7777' 
       WHEN SUBSTR(MGR,0,2) = '78' THEN '8888' 
       ELSE TO_CHAR(MGR)
       END AS CHG_MGR
FROM EMP;